/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.tsx"],
  theme: {
    extend: {},
  },
  corePlugins: [
    'backgroundSize',
    'backgroundColor',
    'backgroundImage',
    'backgroundPosition',
    'backgroundRepeat',
    'boxShadow',
    'boxSizing',
    'borderColor',
    'borderRadius',
    'borderStyle',
    'borderWidth',
    'content',
    'display',
    'flex',
    'flexBasis',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'fontFamily',
    'fontSize',
    'fontWeight',
    'fontStyle',
    'margin',
    'padding',
    'position',
    'opacity',
    'justifyContent',
    'justifyItems',
    'alignContent',
    'alignItems',
    'height',
    'width',
    'maxWidth',
    'maxHeight',
    'minWidth',
    'minHeight',
    'textColor',
    'textAlign',
    'zIndex',
    'verticalAlign',
    'inset'
  ],
  plugins: [],
}
