set_project("app")
set_version("1.0.0")
set_warnings("all")
add_rules("mode.debug", "mode.release")
add_defines("_CRT_SECURE_NO_WARNINGS")
includes("@builtin/xpack")
includes("vendor/LCUI/xmake.lua")

target("app")
    if is_plat("windows") then
        add_rules("win.sdk.application")
        add_files("version.rc")
    end
    set_configdir("include")
    set_rundir("dist")
    add_deps("lcui")
    set_kind("binary")
    add_files("app/**.c")

xpack("app")
    set_title("LCUI Quick Start ($(arch))")
    set_description("A minimal LCUI application")
    set_author("i@lc-soft.io")
    set_maintainer("i@lc-soft.io")
    set_copyright("Copyright (C) 2014-present, Liu Chao <i@lc-soft.io>")
    set_licensefile("./LICENSE.txt")
    set_formats("nsis", "zip")
    set_basename("lcui-quick-start-v$(version)")
    add_installfiles("dist/(**)")
    add_targets("app")
    set_bindir("./")
    set_iconfile("logo.ico")
