name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install xmake
      uses: xmake-io/github-action-setup-xmake@v1.0.1
    - name: setup
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
    - name: lcui-cli
      run: lcui compile ./src
    - name: xmake
      run: xmake
